### PR TITLE
Fixed PR suggestions

### LINKED ISSUE #22: Suggestions
- [x] Use space-y-* instead of mb-6
- [x] Use pageLoader from v2
- [x] Remove flex-row for input field
- [x] move all set states to true for loaders above the try block

### PR DESCRIPTION
**Pull request by shreyakurian02**
Fixes #22 
Used space-y-* instead of mb-6
Used pageLoader from v2
Removed flex-row for input field
Moved all set states to true for loaders above the try block.
Renamed constants , notes and contacts file.

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/NewContactPane.jsx [hunk 1]
```diff
@@ -31,19 +30,17 @@ export default function NewContactPane({ showPane, setShowPane }) {
...
         <Form>
           <Pane.Body>
-            <div>
+            <div className="space-y-3">
               <div className="flex space-x-2">
                 <Input
                   label="First Name"
                   name="firstName"
-                  className="mb-6"
                   required={true}
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Contacts/NewContactPane.jsx:38]: For boolean values, if `true`, we can just pass `required`. 
No need to pass `required = {true}`.

**Review by karthiknmenon — COMMENTED** [review]
@shreyakurian02 A minor suggestion. Please fix it across all pages.
